<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_Capture object_contentFrame</name>
   <tag></tag>
   <elementGuidId>3b366b28-7f06-4aac-80e0-9d576166becf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='contentFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;contentFrame&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>6752dff7-b4d8-4261-9dc0-f283a7aa1718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Home.aspx</value>
      <webElementGuid>053f56fa-d127-453e-adb4-9edc3ea8a295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contentFrame</value>
      <webElementGuid>40ca6704-e322-4675-adb6-f6e4ce57ad71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>YES</value>
      <webElementGuid>e0b6c4ae-27ab-4ce5-bc73-83514c1b9b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frameMenuHome&quot;)/frame[3]</value>
      <webElementGuid>0a78facf-3617-4f7e-a397-3abbd5b3d191</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='contentFrame']</value>
      <webElementGuid>da5d2378-671b-4d2a-8f15-2e8aa153a93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//frameset[@id='frameMenuHome']/frame[3]</value>
      <webElementGuid>ffd4104c-c1e2-4522-b093-f52243f13330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[3]</value>
      <webElementGuid>5c5dcaa7-54ee-4cda-be90-c8e06c5d95cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'Home.aspx' and @name = 'contentFrame']</value>
      <webElementGuid>a40b3f07-8052-4e59-87d3-daf0de7bf7f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
