<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RIM</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>db9dcc07-c519-432e-b4cd-f46ad3ba4375</testSuiteGuid>
   <testCaseLink>
      <guid>c08e30e3-ee3a-4993-94d1-69c127f0f166</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/RIM - Non-Personal/TC09_Amend the Statement Cycle on a Non-Personal Account</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>838affda-420e-40f0-8d0f-178e845c30cb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>333b727a-5417-4f7c-8161-09cc70d58ad1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/RIM - Non-Personal/TC10_Remove a Restriction from a Non-Personal Account</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>daf0c10c-c023-4292-bb86-90a9f9a8d874</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
