<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Transactions</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>042270b0-230d-4b0e-b6b9-150e35981f73</testSuiteGuid>
   <testCaseLink>
      <guid>05f46292-5f31-4b74-9ddd-bf3c60cebfa5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/Credit_Debit Transactions/TC07_Post Credit TC 101 on Commercial Account</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f93b47bd-9a9a-4896-8067-0ae1009e6147</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df3ab98f-ab3b-48b0-b7d1-70dbab490fbf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>934006f7-a296-40ec-9567-c15cefcd0ad6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a570faeb-0ed8-479a-84e7-5e019bb8abaf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/Credit_Debit Transactions/TC08_Post Debit TC 152 on Chequing Account</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2939718f-03db-4451-ad14-7733e0bebf12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03d34765-1318-45fe-b963-6822ceca10d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13f27356-d721-47e7-8cb7-51a4b1780afe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66e31c6c-6fa1-49f0-aa57-06fc8e3e29a0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
