<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Companies</name>
   <tag></tag>
   <elementGuidId>68427d54-c466-4ea0-ac0b-fc03cceaa5bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;OpenItem('/RBLTrinidadQA.BackOfficeUI/Pages/CompaniesFacade.aspx');&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>788a6ad0-1ee2-4124-bb1f-bd8ececfeecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>leftFrame</value>
      <webElementGuid>6c6be259-e7b0-4f8e-a8d1-41393e31de4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OpenItem('/RBLTrinidadQA.BackOfficeUI/Pages/CompaniesFacade.aspx');</value>
      <webElementGuid>c5efd06e-ce70-4f5e-bee4-93fb456c0578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>menu.aspx?tabid=/RBLTrinidadQA.BackOfficeUI/Pages/CompaniesFacade.aspx</value>
      <webElementGuid>a56cccae-f1dc-4644-bddd-5e5b998b5cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                Companies</value>
      <webElementGuid>3f812733-35a3-403d-b1ef-db7861444105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/table[@class=&quot;table-main&quot;]/tbody[1]/tr[1]/td[@class=&quot;backg_logo&quot;]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[@class=&quot;backg_header&quot;]/table[@class=&quot;table_menu&quot;]/tbody[1]/tr[1]/td[@class=&quot;backg_menu&quot;]/table[1]/tbody[1]/tr[2]/td[1]/table[@class=&quot;table_menu_links&quot;]/tbody[1]/tr[1]/td[3]/a[1]</value>
      <webElementGuid>d705dc14-08a5-4c1c-bc04-bb2b67923248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOffice/Page_IC-Banking BackOffice/frame_html1frameset1frame1_topFrame</value>
      <webElementGuid>81d90376-a164-4096-9330-256d8ea091a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;OpenItem('/RBLTrinidadQA.BackOfficeUI/Pages/CompaniesFacade.aspx');&quot;]</value>
      <webElementGuid>f4f16d30-1876-45a0-ae63-47edc86b680f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td[2]/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td[3]/a</value>
      <webElementGuid>54d7a8ef-8b53-43d3-8b38-54cc49e21122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Companies')]</value>
      <webElementGuid>f1cde83f-cc8e-42a6-91bd-fee3950108d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::a[1]</value>
      <webElementGuid>43a33b1d-d82f-4502-8602-8c2a4039ea04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Persons'])[1]/following::a[1]</value>
      <webElementGuid>26a503ec-aa30-4db4-a60e-3b35a9938ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[2]/preceding::a[1]</value>
      <webElementGuid>0a1d564a-c596-48bf-80ed-f8310d3c89f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requests'])[1]/preceding::a[1]</value>
      <webElementGuid>248758dd-877f-4b8a-b9da-ebaced8e77a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Companies']/parent::*</value>
      <webElementGuid>e045b0bb-27ff-455f-9083-c00d665eb5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'menu.aspx?tabid=/RBLTrinidadQA.BackOfficeUI/Pages/CompaniesFacade.aspx')]</value>
      <webElementGuid>519ba423-199e-43b4-93e6-1aa4477f0751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>b4705ccf-8f9f-4a21-8302-1b7d7f9949f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'menu.aspx?tabid=/RBLTrinidadQA.BackOfficeUI/Pages/CompaniesFacade.aspx' and (text() = '
                                                                                Companies' or . = '
                                                                                Companies')]</value>
      <webElementGuid>2c79df5b-f1ab-49ad-ad4b-506fdd0bda9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
