<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_User Administration</name>
   <tag></tag>
   <elementGuidId>252b8404-2285-4c55-ba0d-a9dc5053e39a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;OpenItem('/RBLTrinidadQA.BackOfficeUI/Pages/Administration/SitesUsers.aspx');&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>909b06ec-3957-4943-b9d1-fb05a67a5554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>1d399263-ca0d-4785-a22b-bb6b40482790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OpenItem('/RBLTrinidadQA.BackOfficeUI/Pages/Administration/SitesUsers.aspx');</value>
      <webElementGuid>99ed6aec-6355-4def-918e-f1e6c7ebd824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User Administration</value>
      <webElementGuid>9d0b1971-e03f-4531-bf59-4a49efa773d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableMenuExpanded&quot;)/tbody[1]/tr[8]/td[1]/table[@class=&quot;table_menu_level01&quot;]/tbody[1]/tr[1]/td[@class=&quot;item_level01&quot;]/a[1]</value>
      <webElementGuid>842d8b73-c7cb-438c-9138-30d4ec2a725c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOffice/Page_IC-Banking BackOffice/frame_concat(id(, , frameMenuHome, , )frame_05ff58</value>
      <webElementGuid>7b793a24-d323-40a2-8e9b-d6f446483679</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;OpenItem('/RBLTrinidadQA.BackOfficeUI/Pages/Administration/SitesUsers.aspx');&quot;]</value>
      <webElementGuid>fce1e654-b436-40ec-a0fa-a5d65ae7fc3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tableMenuExpanded']/tbody/tr[8]/td/table/tbody/tr/td/a</value>
      <webElementGuid>61b3fac8-b605-4316-a753-2307c211b3a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'User Administration')]</value>
      <webElementGuid>0f7f1f5d-9a7a-4c3d-8e3d-8d547df23f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Administration']/parent::*</value>
      <webElementGuid>6885b176-f327-4a19-b205-1cd2e27c6a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>190aa7d9-d9da-470e-a7b9-d8a94f2d2e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/table/tbody/tr/td/a</value>
      <webElementGuid>be131903-989b-4fbb-afd7-f0a0002da462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'User Administration' or . = 'User Administration')]</value>
      <webElementGuid>713ea15c-f0ba-4c11-9875-99fa4f5e10d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
