<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_html1frameset1frame1_topFrame</name>
   <tag></tag>
   <elementGuidId>559f9f4a-2e8b-4f48-9344-c376e1392443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='topFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;topFrame&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>5b7cb19b-9837-47ea-bf01-0d723c5b3da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Header.aspx</value>
      <webElementGuid>1d5e01e5-09cd-466d-8e4a-17b9d1cc1485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>topFrame</value>
      <webElementGuid>098c2c03-e66e-40c9-b841-a6e0eb7a67c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>NO</value>
      <webElementGuid>e32f85ff-0d36-4e2e-86fc-dd3c52e22138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>450f039d-a670-462e-9df1-35874240c2f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='topFrame']</value>
      <webElementGuid>ab15435f-cb5d-49f9-b527-6e4cdd0dd4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>ad1a83d6-aa6e-4642-83d4-6fc57ea167bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'Header.aspx' and @name = 'topFrame']</value>
      <webElementGuid>84a44361-a2cc-401a-98cc-63968ec9d4de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
