<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_concat(id(, , frameMenuHome, , )frame_c86c3c</name>
   <tag></tag>
   <elementGuidId>b07459d0-565c-492a-9b5b-7bdb580bfe9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='contentFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;contentFrame&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>a4409af1-4073-4a47-862a-01587529b817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Home.aspx</value>
      <webElementGuid>83fd3572-4190-4772-b2b8-25f9849680e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contentFrame</value>
      <webElementGuid>56206713-2313-47d0-805d-38c5c606cad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>YES</value>
      <webElementGuid>997c7182-38d3-425d-aec5-11b44aa4f1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frameMenuHome&quot;)/frame[3]</value>
      <webElementGuid>7c259fff-5c6d-4d08-8f9f-7f3c39db2206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='contentFrame']</value>
      <webElementGuid>dc918f9c-399f-4c86-9ace-c73f5d5d036a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//frameset[@id='frameMenuHome']/frame[3]</value>
      <webElementGuid>774fe014-00d6-48f5-a751-5b3f2f20106d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[3]</value>
      <webElementGuid>55597762-4232-4c10-b512-dcb49d74f175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'Home.aspx' and @name = 'contentFrame']</value>
      <webElementGuid>f4368223-dfad-4819-b0e6-902ad5833b63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
