<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_concat(id(, , frameMenuHome, , )frame_05ff58</name>
   <tag></tag>
   <elementGuidId>f7afcb23-b8f4-4b05-adfa-7f89249b1327</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='leftFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;leftFrame&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>43476718-4ecf-4053-b142-485a6facc34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Menu.aspx</value>
      <webElementGuid>75750d81-0d3d-4fda-9fcb-4fb7439b78db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leftFrame</value>
      <webElementGuid>a50d9deb-15a8-425c-91b9-dcb3ccdb0972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>NO</value>
      <webElementGuid>b9a157b5-4acc-4470-837b-6b54ee3d0262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frameMenuHome&quot;)/frame[1]</value>
      <webElementGuid>d14c4499-282a-4924-ba74-63a5f8129f6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='leftFrame']</value>
      <webElementGuid>0a1850ff-aebc-44ca-b42a-edadc2487e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//frameset[@id='frameMenuHome']/frame</value>
      <webElementGuid>07e00636-db75-4cca-8d9a-d2e99487c1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset/frameset/frame</value>
      <webElementGuid>005cf89b-2eec-45ac-bf11-58bd74a37d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'Menu.aspx' and @name = 'leftFrame']</value>
      <webElementGuid>0261d156-609c-43cc-9fd2-a62a8bb047c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
