<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_ctl00MainHolderPassword</name>
   <tag></tag>
   <elementGuidId>9c0e3825-d54d-418d-bf8f-bccecdedea5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainHolder_Password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainHolder_Password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fb0b278-019e-403a-bfd9-187e12182bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainHolder$Password</value>
      <webElementGuid>4ce40e12-3981-4c0e-9465-77d9586ac316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>917bb748-f23f-41d4-8530-2875b1cfa327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainHolder_Password</value>
      <webElementGuid>e876d753-7380-40f2-8ea1-ec4c0ace1023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ic-log-form-field</value>
      <webElementGuid>d2275bf8-7975-4dd3-aa60-07409367cf1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5003a663-15ec-4c63-bf69-2ebd92e35d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return validCharactersOnly(this, event, '^[^:;\&lt;>\'\&quot;]*$')</value>
      <webElementGuid>fe948cf0-5303-4248-8a88-a91f5a0eb451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondrop</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>3427ff3e-ef1b-47fc-b5d7-ab93b3582667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>cad54c0d-cbb7-4de7-9686-7214cba982c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainHolder_Password&quot;)</value>
      <webElementGuid>305f6ac7-baf9-47c2-a081-b28e5038b619</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainHolder_Password']</value>
      <webElementGuid>e3cf733c-8e21-462d-bb67-44cf785aec60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_MainHolder_Panel1']/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>9a4caf46-886d-4e64-8b81-1255a9a67c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>df459a36-3707-404a-b3c0-6dc3216236ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainHolder$Password' and @type = 'password' and @id = 'ctl00_MainHolder_Password']</value>
      <webElementGuid>6b83e013-511e-4c60-9d38-3582fd512cc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
