<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_ctl00MainHolderUserName</name>
   <tag></tag>
   <elementGuidId>835d00b7-c3b1-4dfa-b873-4930b9804cb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainHolder_UserName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainHolder_UserName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f3259be-3461-476a-bd76-6341b4b11fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainHolder$UserName</value>
      <webElementGuid>76f05c85-78f0-4cb7-b6f4-b7d5393ff1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7e3c764-a29e-4bc0-9c79-e4912e71cc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainHolder_UserName</value>
      <webElementGuid>2bc90fad-e3ae-4dc5-9ce9-c23d95456b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ic-log-form-field</value>
      <webElementGuid>e9261c9b-2e78-4a3a-8b0a-7cfcf35d324f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7b8b63ee-f53e-4560-acfb-8c671d1535d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return validCharactersOnly(this, event, '^[^:;\&lt;>\'\&quot;]*$')</value>
      <webElementGuid>ea9f05ad-ecb6-490d-a433-089b242b02a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondrop</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>add6060c-22db-4700-a968-9c972dcc8976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>return validCharactersOnly(this, event, '^[^:;\&lt;>\'\&quot;]*$')</value>
      <webElementGuid>980b6c5e-39f5-40cf-953b-9ac73ca133a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainHolder_UserName&quot;)</value>
      <webElementGuid>fcf455cb-4963-4b20-9047-1d1a901b1df0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainHolder_UserName']</value>
      <webElementGuid>1b978c92-9ecc-41bc-9361-7db399c00a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_MainHolder_Panel1']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>f7af6701-aa38-4ee3-93ac-89cfcd3a5da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>2909b0bc-0817-46e6-acd6-a025fe0e3054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainHolder$UserName' and @type = 'text' and @id = 'ctl00_MainHolder_UserName']</value>
      <webElementGuid>b5b780d7-39df-4414-8de1-907e4aafbd02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
