<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Site Name_ctl00MainHolderCompaniesSitesFiltertxtSiteName</name>
   <tag></tag>
   <elementGuidId>c08292fd-b008-4235-b96d-4320e7eee481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainHolder_CompaniesSitesFilter_txtSiteName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainHolder_CompaniesSitesFilter_txtSiteName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60251519-7154-4cd1-81b9-95f37b18284a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainHolder$CompaniesSitesFilter$txtSiteName</value>
      <webElementGuid>dbd859a3-b30c-429e-b7aa-bb63993882d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>22fbd741-edd7-49e3-bd39-9430bb846e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>37057e65-61f9-4cae-b24d-13564d85c4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainHolder_CompaniesSitesFilter_txtSiteName</value>
      <webElementGuid>b77e59c5-b87a-496d-9fd5-884949d5aab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return validCharactersOnly(this, event, '^[^:;\&lt;>\'\&quot;]*$')</value>
      <webElementGuid>21eda49f-6779-4438-bfa3-c0b46359f252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondrop</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>80fb1a4c-91ba-4c2d-8cba-e227625fa3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>return validCharactersOnly(this, event, '^[^:;\&lt;>\'\&quot;]*$')</value>
      <webElementGuid>bea1d696-c064-41b6-9344-3ca3cfda4641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a6bb4379-5f6d-4098-91eb-cd0419b7598b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainHolder_CompaniesSitesFilter_txtSiteName&quot;)</value>
      <webElementGuid>6de7a488-6dc2-4b94-8f35-ba589a4f5f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOffice/Page_IC-Banking BackOffice/frame_concat(id(, , frameMenuHome, , )frame_c86c3c</value>
      <webElementGuid>78031dd5-5ac4-4638-883b-9b772026eb10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainHolder_CompaniesSitesFilter_txtSiteName']</value>
      <webElementGuid>d06d04b8-c184-469a-8273-7e459ce3db63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/ul/li[2]/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>f50ff07e-7c3a-4536-bfca-8f9014655782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>833a41f2-7082-422f-be14-8c773dc425cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainHolder$CompaniesSitesFilter$txtSiteName' and @type = 'text' and @id = 'ctl00_MainHolder_CompaniesSitesFilter_txtSiteName']</value>
      <webElementGuid>667dc33c-1b42-408f-8773-7cb43437473c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
