<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_olawrence</name>
   <tag></tag>
   <elementGuidId>5078a028-0ca4-4a0c-a355-4c9e030bfb1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='ctl00_MainHolder_SiteAdministratorsGrid_DXDataRow0']/td[${index}]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c95ccf01-9493-439e-bf27-4b3759093646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxgv</value>
      <webElementGuid>090aa01e-b879-4bfd-9c78-9762863e927c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>olawrence</value>
      <webElementGuid>31101b6b-b02a-4da2-9dc1-3c38cb1c672f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainHolder_SiteAdministratorsGrid_DXDataRow0&quot;)/td[@class=&quot;dxgv&quot;]</value>
      <webElementGuid>afc41712-8498-4c06-bdbb-7118d033a2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOffice/Page_IC-Banking BackOffice/frame_concat(id(, , frameMenuHome, , )frame_c86c3c</value>
      <webElementGuid>ecaf9731-7c51-49c4-b528-cb7495a002d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_MainHolder_SiteAdministratorsGrid_DXDataRow0']/td[2]</value>
      <webElementGuid>1b5e202b-0e82-48a0-8edd-13ade62cff9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading…'])[1]/following::td[3]</value>
      <webElementGuid>abf8c915-3159-4cb0-bea5-3d8bd3bfa422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrator'])[1]/following::td[8]</value>
      <webElementGuid>fe63675b-99d0-41e8-94eb-9155f7a1c9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Omari'])[1]/preceding::td[1]</value>
      <webElementGuid>25710ca3-22c0-4d46-a352-4d5973d3054b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lawrence'])[1]/preceding::td[2]</value>
      <webElementGuid>5f53f347-0581-4121-8117-cb3ab1222721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='olawrence']/parent::*</value>
      <webElementGuid>ec4b50fc-65ab-4e92-8c9b-1b90dd24362d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>d0903693-a4ab-4732-9dd2-033f5ef2e2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'olawrence' or . = 'olawrence')]</value>
      <webElementGuid>9f153895-aa98-4f72-906e-8c1e72b8ca93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
