<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Site Administrators_ctl00_MainHolder_Sit_67fe71</name>
   <tag></tag>
   <elementGuidId>4328fe0f-1691-453f-96ea-8993bb2768a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='ctl00_MainHolder_SiteAdministratorsGrid_DX-DT-col0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainHolder_SiteAdministratorsGrid_DX-DT-col0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3701bcef-287b-4da4-a36b-9617a0acdfe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainHolder_SiteAdministratorsGrid_DX-DT-col0</value>
      <webElementGuid>9e8c1cc4-11f7-44e9-a569-3ff74837a2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxgvHeader</value>
      <webElementGuid>6d524144-21c8-43c7-9a9c-4fd21b5f7448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>aspxGVHeaderMouseDown('ctl00_MainHolder_SiteAdministratorsGrid', this, event);</value>
      <webElementGuid>2a07fd54-bd51-400a-9db4-6aeb6c4e4605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainHolder_SiteAdministratorsGrid_DX-DT-col0&quot;)</value>
      <webElementGuid>4bb578c9-942a-45f8-9b98-2fb42ecb6508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOffice/Page_IC-Banking BackOffice/frame_concat(id(, , frameMenuHome, , )frame_c86c3c</value>
      <webElementGuid>9ecefddf-1f8e-422e-b7ac-4b43ab6f219a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='ctl00_MainHolder_SiteAdministratorsGrid_DX-DT-col0']</value>
      <webElementGuid>a4f86720-416c-4aba-9a1d-f4fac09a4d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_MainHolder_SiteAdministratorsGrid_DXHeadersRow']/td</value>
      <webElementGuid>573a61b6-0866-4eab-b01b-47737a68165c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site Administrators'])[1]/following::td[4]</value>
      <webElementGuid>55cf42d8-efe3-40ff-9f6d-d646f4d13860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::td[8]</value>
      <webElementGuid>f89d10d8-805f-4ba2-84b0-47da6031adb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/preceding::td[2]</value>
      <webElementGuid>9e4c6b2a-8396-4bf5-ba3b-a6ada5b41e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::td[4]</value>
      <webElementGuid>d5b7b975-bce3-4214-8158-de3ae180d0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/table/tbody/tr/td</value>
      <webElementGuid>273e55dc-3e3c-44b0-bc97-e9ebc8901a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'ctl00_MainHolder_SiteAdministratorsGrid_DX-DT-col0']</value>
      <webElementGuid>31f30976-6b6e-4c56-8f3b-0e73a620a95c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
