<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Username</name>
   <tag></tag>
   <elementGuidId>b6f5453f-4f29-453c-b496-aeca4b1a7788</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='ctl00_MainHolder_SiteAdministratorsGrid_DX-GSDT-col2']/table/tbody/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainHolder_SiteAdministratorsGrid_DX-GSDT-col2 > table > tbody > tr > td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c54cc888-3262-42b7-8bf8-2e682cc2d0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>2849234a-552d-4ac8-80b2-7a1790bd0179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainHolder_SiteAdministratorsGrid_DX-GSDT-col2&quot;)/table[1]/tbody[1]/tr[1]/td[1]</value>
      <webElementGuid>f713669e-3926-400e-abf7-9393dac08431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOffice/Page_IC-Banking BackOffice/frame_concat(id(, , frameMenuHome, , )frame_c86c3c</value>
      <webElementGuid>68deaf7e-19a1-4285-81af-c89ef5db2d16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_MainHolder_SiteAdministratorsGrid_DX-GSDT-col2']/table/tbody/tr/td</value>
      <webElementGuid>1dd4ed2e-34be-4861-8a63-9fe767095c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site Administrators'])[1]/following::td[7]</value>
      <webElementGuid>a565d22d-610a-469b-b940-b812e08e396a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::td[11]</value>
      <webElementGuid>4f71ca85-5e1c-416b-a04d-9787370bcd02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::td[1]</value>
      <webElementGuid>28b28e50-80bc-46cc-8c3a-39edb45eca6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/preceding::td[3]</value>
      <webElementGuid>d4b31413-411c-415e-ad48-a3c4704fa849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Username']/parent::*</value>
      <webElementGuid>b89448bf-01c8-4c4b-990e-819cd6ecfd4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td</value>
      <webElementGuid>df72167c-61a7-4ef3-a031-cb9aea672daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Username' or . = 'Username')]</value>
      <webElementGuid>4234027c-6aaa-4322-b7fe-9a4177385829</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
